name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'
      - name: Install dependencies
        run: cd backend && go mod tidy
      - name: Run tests
        env:
          JWT_SECRET: testsecret
        run: cd backend && go test -v ./...
      - name: Generate coverage report
        env:
          JWT_SECRET: testsecret
        run: |
          cd backend
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
